package th.or.innova.skima2013.view;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class CountryList implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private List<Country> list;
	
	public List<Country> getList() {
		return list;
	}
	public void setList(List<Country> list) {
		this.list = list;
	}

	public CountryList() {
		list = new ArrayList<Country>();
		list.add(new Country("Afghanistan"));
		list.add(new Country("Albania"));
		list.add(new Country("Algeria"));
		list.add(new Country("American Samoa"));
		list.add(new Country("Andorra"));
		list.add(new Country("Angola"));
		list.add(new Country("Anguilla"));
		list.add(new Country("Antigua &amp; Barbuda"));
		list.add(new Country("Argentina"));
		list.add(new Country("Armenia"));
		list.add(new Country("Aruba"));
		list.add(new Country("Australia"));
		list.add(new Country("Austria"));
		list.add(new Country("Azerbaijan"));
		list.add(new Country("Bahamas"));
		list.add(new Country("Bahrain"));
		list.add(new Country("Bangladesh"));
		list.add(new Country("Barbados"));
		list.add(new Country("Belarus"));
		list.add(new Country("Belgium"));
		list.add(new Country("Belize"));
		list.add(new Country("Benin"));
		list.add(new Country("Bermuda"));
		list.add(new Country("Bhutan"));
		list.add(new Country("Bolivia"));
		list.add(new Country("Bonaire"));
		list.add(new Country("Bosnia &amp; Herzegovina"));
		list.add(new Country("Botswana"));
		list.add(new Country("Brazil"));
		list.add(new Country("British Indian Ocean Ter"));
		list.add(new Country("Brunei"));
		list.add(new Country("Bulgaria"));
		list.add(new Country("Burkina Faso"));
		list.add(new Country("Burundi"));
		list.add(new Country("Cambodia"));
		list.add(new Country("Cameroon"));
		list.add(new Country("Canada"));
		list.add(new Country("Canary Islands"));
		list.add(new Country("Cape Verde"));
		list.add(new Country("Cayman Islands"));
		list.add(new Country("Central African Republic"));
		list.add(new Country("Chad"));
		list.add(new Country("Channel Islands"));
		list.add(new Country("Chile"));
		list.add(new Country("China"));
		list.add(new Country("Christmas Island"));
		list.add(new Country("Cocos Island"));
		list.add(new Country("Colombia"));
		list.add(new Country("Comoros"));
		list.add(new Country("Congo"));
		list.add(new Country("Cook Islands"));
		list.add(new Country("Costa Rica"));
		list.add(new Country("Cote D'Ivoire"));
		list.add(new Country("Croatia"));
		list.add(new Country("Cuba"));
		list.add(new Country("Curacao"));
		list.add(new Country("Cyprus"));
		list.add(new Country("Czech Republic"));
		list.add(new Country("Denmark"));
		list.add(new Country("Djibouti"));
		list.add(new Country("Dominica"));
		list.add(new Country("Dominican Republic"));
		list.add(new Country("East Timor"));
		list.add(new Country("Ecuador"));
		list.add(new Country("Egypt"));
		list.add(new Country("El Salvador"));
		list.add(new Country("Equatorial Guinea"));
		list.add(new Country("Eritrea"));
		list.add(new Country("Estonia"));
		list.add(new Country("Ethiopia"));
		list.add(new Country("Falkland Islands"));
		list.add(new Country("Faroe Islands"));
		list.add(new Country("Fiji"));
		list.add(new Country("Finland"));
		list.add(new Country("France"));
		list.add(new Country("French Guiana"));
		list.add(new Country("French Polynesia"));
		list.add(new Country("French Southern Ter"));
		list.add(new Country("Gabon"));
		list.add(new Country("Gambia"));
		list.add(new Country("Georgia"));
		list.add(new Country("Germany"));
		list.add(new Country("Ghana"));
		list.add(new Country("Gibraltar"));
		list.add(new Country("Great Britain"));
		list.add(new Country("Greece"));
		list.add(new Country("Greenland"));
		list.add(new Country("Grenada"));
		list.add(new Country("Guadeloupe"));
		list.add(new Country("Guam"));
		list.add(new Country("Guatemala"));
		list.add(new Country("Guinea"));
		list.add(new Country("Guyana"));
		list.add(new Country("Haiti"));
		list.add(new Country("Hawaii"));
		list.add(new Country("Honduras"));
		list.add(new Country("Hong Kong"));
		list.add(new Country("Hungary"));
		list.add(new Country("Iceland"));
		list.add(new Country("India"));
		list.add(new Country("Indonesia"));
		list.add(new Country("Iran"));
		list.add(new Country("Iraq"));
		list.add(new Country("Ireland"));
		list.add(new Country("Isle of Man"));
		list.add(new Country("Israel"));
		list.add(new Country("Italy"));
		list.add(new Country("Jamaica"));
		list.add(new Country("Japan"));
		list.add(new Country("Jordan"));
		list.add(new Country("Kazakhstan"));
		list.add(new Country("Kenya"));
		list.add(new Country("Kiribati"));
		list.add(new Country("Korea North"));
		list.add(new Country("Korea South"));
		list.add(new Country("Kuwait"));
		list.add(new Country("Kyrgyzstan"));
		list.add(new Country("Laos"));
		list.add(new Country("Latvia"));
		list.add(new Country("Lebanon"));
		list.add(new Country("Lesotho"));
		list.add(new Country("Liberia"));
		list.add(new Country("Libya"));
		list.add(new Country("Liechtenstein"));
		list.add(new Country("Lithuania"));
		list.add(new Country("Luxembourg"));
		list.add(new Country("Macau"));
		list.add(new Country("Macedonia"));
		list.add(new Country("Madagascar"));
		list.add(new Country("Malaysia"));
		list.add(new Country("Malawi"));
		list.add(new Country("Maldives"));
		list.add(new Country("Mali"));
		list.add(new Country("Malta"));
		list.add(new Country("Marshall Islands"));
		list.add(new Country("Martinique"));
		list.add(new Country("Mauritania"));
		list.add(new Country("Mauritius"));
		list.add(new Country("Mayotte"));
		list.add(new Country("Mexico"));
		list.add(new Country("Midway Islands"));
		list.add(new Country("Moldova"));
		list.add(new Country("Monaco"));
		list.add(new Country("Mongolia"));
		list.add(new Country("Montserrat"));
		list.add(new Country("Morocco"));
		list.add(new Country("Mozambique"));
		list.add(new Country("Myanmar"));
		list.add(new Country("Nambia"));
		list.add(new Country("Nauru"));
		list.add(new Country("Nepal"));
		list.add(new Country("Netherland Antilles"));
		list.add(new Country("Netherlands (Holland, Europe)"));
		list.add(new Country("Nevis"));
		list.add(new Country("New Caledonia"));
		list.add(new Country("New Zealand"));
		list.add(new Country("Nicaragua"));
		list.add(new Country("Niger"));
		list.add(new Country("Nigeria"));
		list.add(new Country("Niue"));
		list.add(new Country("Norfolk Island"));
		list.add(new Country("Norway"));
		list.add(new Country("Oman"));
		list.add(new Country("Pakistan"));
		list.add(new Country("Palau Island"));
		list.add(new Country("Palestine"));
		list.add(new Country("Panama"));
		list.add(new Country("Papua New Guinea"));
		list.add(new Country("Paraguay"));
		list.add(new Country("Peru"));
		list.add(new Country("Philippines"));
		list.add(new Country("Pitcairn Island"));
		list.add(new Country("Poland"));
		list.add(new Country("Portugal"));
		list.add(new Country("Puerto Rico"));
		list.add(new Country("Qatar"));
		list.add(new Country("Republic of Montenegro"));
		list.add(new Country("Republic of Serbia"));
		list.add(new Country("Reunion"));
		list.add(new Country("Romania"));
		list.add(new Country("Russia"));
		list.add(new Country("Rwanda"));
		list.add(new Country("St Barthelemy"));
		list.add(new Country("St Eustatius"));
		list.add(new Country("St Helena"));
		list.add(new Country("St Kitts-Nevis"));
		list.add(new Country("St Lucia"));
		list.add(new Country("St Maarten"));
		list.add(new Country("St Pierre &amp; Miquelon"));
		list.add(new Country("St Vincent &amp; Grenadines"));
		list.add(new Country("Saipan"));
		list.add(new Country("Samoa"));
		list.add(new Country("Samoa American"));
		list.add(new Country("San Marino"));
		list.add(new Country("Sao Tome &amp; Principe"));
		list.add(new Country("Saudi Arabia"));
		list.add(new Country("Senegal"));
		list.add(new Country("Seychelles"));
		list.add(new Country("Sierra Leone"));
		list.add(new Country("Singapore"));
		list.add(new Country("Slovakia"));
		list.add(new Country("Slovenia"));
		list.add(new Country("Solomon Islands"));
		list.add(new Country("Somalia"));
		list.add(new Country("South Africa"));
		list.add(new Country("Spain"));
		list.add(new Country("Sri Lanka"));
		list.add(new Country("Sudan"));
		list.add(new Country("Suriname"));
		list.add(new Country("Swaziland"));
		list.add(new Country("Sweden"));
		list.add(new Country("Switzerland"));
		list.add(new Country("Syria"));
		list.add(new Country("Tahiti"));
		list.add(new Country("Taiwan"));
		list.add(new Country("Tajikistan"));
		list.add(new Country("Tanzania"));
		list.add(new Country("Thailand"));
		list.add(new Country("Togo"));
		list.add(new Country("Tokelau"));
		list.add(new Country("Tonga"));
		list.add(new Country("Trinidad &amp; Tobago"));
		list.add(new Country("Tunisia"));
		list.add(new Country("Turkey"));
		list.add(new Country("Turkmenistan"));
		list.add(new Country("Turks &amp; Caicos Is"));
		list.add(new Country("Tuvalu"));
		list.add(new Country("Uganda"));
		list.add(new Country("Ukraine"));
		list.add(new Country("United Arab Emirates"));
		list.add(new Country("United Kingdom"));
		list.add(new Country("United States of America"));
		list.add(new Country("Uruguay"));
		list.add(new Country("Uzbekistan"));
		list.add(new Country("Vanuatu"));
		list.add(new Country("Vatican City State"));
		list.add(new Country("Venezuela"));
		list.add(new Country("Vietnam"));
		list.add(new Country("Virgin Islands (Brit)"));
		list.add(new Country("Virgin Islands (USA)"));
		list.add(new Country("Wake Island"));
		list.add(new Country("Wallis &amp; Futana Is"));
		list.add(new Country("Yemen"));
		list.add(new Country("Zaire"));
		list.add(new Country("Zambia"));
		list.add(new Country("Zimbabwe"));
	}
	
}
